#pragma once

inline constexpr char *DEV_NAME = "dev_name";
char devName[30] = {};
inline constexpr char *PARAM_CMD1 = "cmd1";
inline constexpr char *MAX_ZAWOR = "param1";
inline constexpr char *MIN_ZAWOR = "param2";
inline constexpr char *MIN_POMPA = "param3";
inline constexpr char *GORNA_WARTOSC = "param5";
inline constexpr char *DOLNA_WARTOSC = "param6";
inline constexpr char *MAX_POZIOM = "param8";
uint32_t gornaWartosc = 4095;
uint32_t dolnaWartosc = 0;
uint32_t maxPoziom = 95;
uint32_t maxZawor = 60;
uint32_t minZawor = 20;
uint32_t minPompa = 10;
inline constexpr char *USTAW_MINIMUM = "ustaw_minimum";
uint8_t ustawMinimum = OFF;
inline constexpr char *USTAW_MAKSIMUM = "ustaw_maksimum";
uint8_t ustawMaksimum = OFF;
bool dolej = false;
bool odczyt = false;
int32_t aktualnyPoziom;
inline constexpr char *NAN_VALUE = "nan_value";
int32_t nanValue = -1;
inline constexpr char *RAW_VALUE = "raw_value";
inline constexpr char *KRANCOWKI = "krancowki_";
uint8_t Krancowki = OFF;
inline constexpr char *CZUJNIK_TEMPERATURY = "czujnik_temperatury";
uint8_t CzujnikTemperatury = OFF;
