#pragma once

const char DEV_NAME[] = "dev_name";
char devName[30] = {};
const char PARAM_CMD1[] = "cmd1";
const char MAX_ZAWOR[] = "param1";
const char MIN_ZAWOR[] = "param2";
const char MIN_POMPA[] = "param3";
const char GORNA_WARTOSC[] = "param5";
const char DOLNA_WARTOSC[] = "param6";
const char MAX_POZIOM[] = "param8";
uint32_t gornaWartosc = 4095;
uint32_t dolnaWartosc = 0;
uint32_t maxPoziom = 95;
uint32_t maxZawor = 60;
uint32_t minZawor = 20;
uint32_t minPompa = 10;
const char USTAW_MINIMUM[] = "ustaw_minimum";
uint8_t ustawMinimum = OFF;
const char USTAW_MAKSIMUM[] = "ustaw_maksimum";
uint8_t ustawMaksimum = OFF;
bool dolej = false;
bool odczyt = false;
int32_t aktualnyPoziom;
const char NAN_VALUE[] = "nan_value";
int32_t nanValue = -1;
const char RAW_VALUE[] = "raw_value";
const char KRANCOWKI[] = "krancowki_";
uint8_t Krancowki = OFF;
const char CZUJNIK_TEMPERATURY[] = "czujnik_temperatury";
uint8_t CzujnikTemperatury = OFF;